# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.crawler:
        class: AppBundle\Service\Crawler
        arguments: ['%hub_url%', '%hub_depth%', '@doctrine.orm.entity_manager']
